DESIRED = ['First Name','Last Name','Title','Email Address','Account Name','Mailing Address 1','Mailing Address 2','City','State','Zip','Optional Address 1','Optional Address 2','Optional City','Optional State','Optional Zip','Account Type','Customer Type','Employees','Industry','Phone 1','Phone 2 (EXT)','Phone 3 (Mobile)','Salutation','Salesperson','Customer_Prospect_Dormant','Service of Interest']

MAPPING = {
    'First': 'First Name',
    'Last': 'Last Name',
    'Email': 'Email Address',
    'Acccount Name': 'Account Name',
    'Company': 'Account Name',
    'Mailing Address 1 ': 'Mailing Address 1',
    'Optional  Address 1': 'Optional Address 1',
    'Optional  Address 2': 'Optional Address 2',
    'Optional Mailing Address 2': 'Optional Address 2',
    'Address': 'Mailing Address 1',
    'Address 1': 'Mailing Address 1',
    'Address 2': 'Mailing Address 2',
    'State ': 'State',
    'State .1': 'Optional State',
    'State or Province': 'State',
    '_State_or_Province': 'State',
    'Zip ': 'Zip',
    'Zip .1': 'Zip.1',
    'Zip Code': 'Zip',
    'Zip Code.1': 'Zip.1',
    'Zip or Postal Code': 'Zip',
    '_Zip_or_Postal_Code': 'Zip',
    'Industry ': 'Industry',
    'Phone': 'Phone 1',
    'Phone 1 ': 'Phone 1',
    'Phone 2 (EXT': 'Phone 2 (EXT)',
    'Phone 2 (Ext)': 'Phone 2 (EXT)',
    'Phone 2': 'Phone 2 (EXT)',
    'Phone 2 (EXT) ': 'Phone 2 (EXT)',
    'Phone 3 (Mobile) ': 'Phone 3 (Mobile)',
    'Saluatation': 'Salutation',
    'Sales Person': 'Salesperson',
    'Customer/Prospect/Dormant': 'Customer_Prospect_Dormant',
    'Customer_Prospect_Dominant': 'Customer_Prospect_Dormant',
    'Service Of Interest': 'Service of Interest',
    'Product /Solution of Interest': 'Service of Interest',
    'Product _Solution of Interest': 'Service of Interest',
    'City.1': 'Optional City',
    'State.1': 'Optional State',
    'Zip.1': 'Optional Zip',
}

APIMAPPING = {
    'First Name': 'FirstName',
    'Last Name': 'LastName',
    'Title': 'JobTitle',
    'Email Address': 'Email',
    'Account Name': 'Company',
    'Mailing Address 1': 'StreetAddress1',
    'Mailing Address 2': 'StreetAddress2',
    'City': 'City',
    'State': 'State',
    'Zip': 'PostalCode',
    'Optional Address 1': 'Address2Street1',
    'Optional Address 2': 'Address2Street2',
    'City.1': 'City2',
    'State.1': 'State2',
    'Zip.1': 'PostalCode2',
    'Account Type': 'Account Type',
    'Customer Type': 'ContactType',
    'Employees': 'Employees',
    'Industry': 'Industry',
    'Phone 1': 'Phone1',
    'Phone 2 (Ext)': 'Phone1Ext',
    'Phone 3 (Mobile)': 'Phone2',
    'Salutation': 'Title',
    'Salesperson': 'Salesperson',
    'Customer_Prospect_Dormant': 'Customer_Prospect_Dormant',
    'Service of Interest': 'Service of Interest',
}